# Generated by Django 3.1.5 on 2021-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.CharField(max_length=64)),
                ('date_of_death', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('native_language', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('publish_year', models.PositiveSmallIntegerField()),
                ('review', models.CharField(max_length=512)),
                ('condition', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
